### ISSUE TITLE
Create a ML Model which give score when a user upload a resume

### ISSUE THREAD

**Issue by Ayushpanditmoto** [Ayushpanditmoto/projectshub#37]

**Comment by k7kaushal** [comment]
Hi @Ayushpanditmoto, 
I've been interested in working on open-source projects for quite a while now, Hacktoberfest seems to my starting point in this journey ahead, being new to open-source I feel your issue is a good first contribution for me to start with.
I would like to know more about the parameters you want to use to score a resume (e.g. language, length, details, etc) and if you're looking for any specific algorithm to implement here.
I would like the opportunity to contribute to this issue.

**Comment by Ayushpanditmoto** [comment]
@k7kaushal actually you can research on this topic came up with better solution ,
Like there many website who give scores on resume , i don't know about ML you have to do this on your own

**Comment by ananyapillai72** [comment]
Hey! I would like to work on this project. I have done projects in ML, but not explored this domain. It would be great if you assign me.

**Comment by Ayushpanditmoto** [comment]
@ananyapillai72 assigned

**Comment by Ayushpanditmoto** [comment]
make sure you start the repo

**Comment by ananyapillai72** [comment]
Yes, I have stared the repo
Also, the model has been trained and will upload the same

**Comment by Ayushpanditmoto** [comment]
@ananyapillai72 damn okay also create a new issues like create api for this model
