### ISSUE TITLE
Improve icon and text

### ISSUE THREAD

**Issue by Ayushpanditmoto** [Ayushpanditmoto/projectshub#58]
![Screenshot_1](https://github.com/Ayushpanditmoto/projectshub/assets/31253617/4b9bf5c0-df47-488b-9cfc-0ebb9e2b6605)
Add Text and Icon related to content

**Comment by rizzabh** [comment]
Hey, I feel like i can contribute to this repo, can you be more precise about what you want to get done for this issue?

**Comment by Ayushpanditmoto** [comment]
@rizzabh actually i want it should look good you may add any good images with text button like that or inspire from any website

**Comment by rizzabh** [comment]
Oh got it, so i better not alter any text content just the ui.

**Comment by Ayushpanditmoto** [comment]
text will be same as written there only thing is look should attractive and simple

**Comment by shivamsethi** [comment]
@Ayushpanditmoto  - I can improve it. Can you assign this to me?

**Comment by shivamsethi** [comment]
@Ayushpanditmoto  - Is there a requirement to stick with the current blue color or can I experiment with it? Or maybe make all four buttons different colors/shades?

**Comment by Ayushpanditmoto** [comment]
@shivamsethi before staring any design show me any demo design , you experiment with it  i  am expecting may be  icon or images not button with gradient try to see different website what they are using

**Comment by shivamsethi** [comment]
@Ayushpanditmoto  - Sharing here a couple of inspirations. Best to use icons instead of images due to size being very small.


1.
<img width="807" alt="image" src="https://github.com/Ayushpanditmoto/projectshub/assets/22752944/ce8ba2d3-9e40-47f9-8b18-82ae998c0b8b">
.

.

.
2.
<img width="761" alt="image" src="https://github.com/Ayushpanditmoto/projectshub/assets/22752944/53efd93e-aa61-47ed-a95b-1f6549991a5c">
.

.

.
3.
<img width="778" alt="image" src="https://github.com/Ayushpanditmoto/projectshub/assets/22752944/bfa883c5-8929-451a-b33f-d8363aa4f46c">

.

.

.

4.
![image](https://github.com/Ayushpanditmoto/projectshub/assets/22752944/b11ce83d-2379-4ac5-b60f-239d042258ec)

.
.

.
.
Inspirations found from [here](https://flowbite.com/docs/components/buttons/) and [here](https://postsrc.com/components/buttons/button-with-icon)

**Comment by Ayushpanditmoto** [comment]
1st one good

**Comment by shivamsethi** [comment]
@Ayushpanditmoto - okay. Should we proceed with colored or bnw icons?

**Comment by Ayushpanditmoto** [comment]
@shivamsethi find some relevant icons matching with text 😬

**Comment by shivamsethi** [comment]
@Ayushpanditmoto  - I will find for sure, no worries. But one question, do you have a preference for colored image like icons or black and white mono colored icons? Or are you flexible?

**Comment by Ayushpanditmoto** [comment]
before making any pr just show me what you have made as such no requirements but looks should be professional

**Comment by shivamsethi** [comment]
@Ayushpanditmoto  - Feedbacks please :)

<img width="1155" alt="image" src="https://github.com/Ayushpanditmoto/projectshub/assets/22752944/c48ffcee-87b1-44d1-8248-bbbeb3a2914d">

**Comment by Ayushpanditmoto** [comment]
Its looks awesome is it mobile responsive ??

**Comment by Ayushpanditmoto** [comment]
Awesome work 🔥🔥

**Comment by shivamsethi** [comment]
@Ayushpanditmoto - I will raise the PR in sometime :)

**Comment by Ayushpanditmoto** [comment]
@shivamsethi  Okay
